### ISSUE TITLE
SwiftOCA.OcaStatus.notImplemented

### ISSUE THREAD

**Issue by mattcph** [PADL/ocacli#1] opened 2024-03-19 09:59 UTC
When using cd to enter OcaBlocks, the return is status(SwiftOCA.OcaStatus.notImplemented)
Reproduce using aes70x.net:65000

However, some VM's did work but unsure on whether they are replying with OcaStatus.

```
 % ./ocacli -h 10.0.0.229 -p 65000
2024-03-19T10:55:42+0100 info com.padl.SwiftOCA : [SwiftOCA] Connected to oca/tcp/10.0.0.229:65000
/> cat 
actionObjects: ["/Channel 1"]
classID: 1.1.3
classVersion: 3
enabled: true
globalType: null
label: null
latency: null
lockState: null
lockable: false
mostRecentParamSetIdentifier: null
oNoMap: null
objectNumber: 100
owner: null
portClockMap: null
ports: []
role: 
signalPaths: null
type: null
/> ls 
Channel 1
/> cd Channel 1 
status(SwiftOCA.OcaStatus.notImplemented)
/> ls 
Channel 1
/> 
```

**Comment by lhoward** [comment] 2024-03-19 10:56
Currently it requires the device to implement `FindActionObjectsByPath()`. I can add a fallback that traverses the block hierarchy manually.

**Comment by lhoward** [comment] 2024-03-22 11:24
Ah, OK, the problem is also that `GetPath()` isn't implemented. I'll have a fix shortly.

**Comment by lhoward** [comment] 2024-03-26 19:25
Should be fixed now.

**Closed as completed by lhoward** 2024-03-26 19:25 UTC
